# Generated by Django 5.2.15 on 2026-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprise/')),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone_principal', models.CharField(blank=True, max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('numero_fiscal', models.CharField(blank=True, max_length=100)),
                ('monnaie', models.CharField(default='FCFA', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'db_table': 'entreprise',
            },
        ),
    ]
