# Generated by Django 5.2.15 on 2026-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='numero_fiscal',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='numero_ifu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro IFU'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registre de commerce'),
        ),
    ]
