services:
  - type: web
    name: isowo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn isowo.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    plan: free
