# Generated by Django 5.2.15 on 2026-06-09 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('partiel', 'Partiel'), ('annule', 'Annulé')], default='valide', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='fournisseurs.fournisseur')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat fournisseur',
                'db_table': 'achats_fournisseurs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.achatfournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achat', to='produits.produit')),
            ],
            options={
                'db_table': 'lignes_achat',
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='achats.achatfournisseur')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='fournisseurs.fournisseur')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'db_table': 'paiements_fournisseurs',
                'ordering': ['-date'],
            },
        ),
    ]
