# Generated by Django 5.2.15 on 2026-06-09 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PretArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('beneficiaire', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_pret', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('partiel', 'Partiel')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_argent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Prêt d'argent",
                'db_table': 'prets_argent',
                'ordering': ['-date_pret'],
            },
        ),
        migrations.CreateModel(
            name='PretMarchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('beneficiaire', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('quantite_rendue', models.IntegerField(default=0)),
                ('mode_remboursement', models.CharField(choices=[('produit', 'Restitution produit'), ('argent', 'Remboursement argent')], default='produit', max_length=20)),
                ('montant_equivalent', models.DecimalField(decimal_places=2, default=0, help_text='Valeur en argent si remboursement en argent', max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_pret', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('partiel', 'Partiel')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='produits.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_marchandises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prêt de marchandise',
                'db_table': 'prets_marchandises',
                'ordering': ['-date_pret'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='prets.pretargent')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_argent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remboursements_argent',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementMarchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_rendue', models.IntegerField(default=0)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='prets.pretmarchandise')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_marchandises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remboursements_marchandises',
                'ordering': ['-date'],
            },
        ),
    ]
