# Generated by Django 5.2.15 on 2026-06-10 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('annulation', 'Annulation'), ('paiement', 'Paiement'), ('connexion', 'Connexion')], max_length=20)),
                ('module', models.CharField(choices=[('ventes', 'Ventes'), ('achats', 'Achats'), ('clients', 'Clients'), ('fournisseurs', 'Fournisseurs'), ('produits', 'Produits'), ('stock', 'Stock'), ('paiements', 'Paiements'), ('prets', 'Prêts'), ('utilisateurs', 'Utilisateurs'), ('auth', 'Authentification')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Historique des actions',
                'db_table': 'historique_actions',
                'ordering': ['-date'],
            },
        ),
    ]
