# Generated by Django 5.2.15 on 2026-06-09 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('nom_contact', models.CharField(blank=True, max_length=100)),
                ('prenom_contact', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delai_paiement', models.IntegerField(default=0, help_text='Délai habituel en jours')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'db_table': 'fournisseurs',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='FournisseurTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('compagnie', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('principal', 'Principal'), ('secondaire', 'Secondaire'), ('professionnel', 'Professionnel')], default='principal', max_length=20)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='fournisseurs.fournisseur')),
            ],
            options={
                'db_table': 'fournisseur_telephones',
            },
        ),
    ]
