# Generated by Django 5.2.15 on 2026-06-09 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('poids_volume', models.CharField(blank=True, max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='categories.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'db_table': 'produits',
                'ordering': ['nom'],
            },
        ),
    ]
